### ISSUE TITLE
custom_objects_spec misses deletecollection operations

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/gen#131]
[The custom object openapi spec](https://github.com/kubernetes-client/gen/blob/master/openapi/custom_objects_spec.json) misses deletecollection operations for cluster-scoped and namespaced custom objects. These operations are supported in apiserver. We should add them to the spec and regenerate the clients.

cc @scottilee

**Comment by scottilee** [comment]
@roycaihw where could I find the json content to use, particularly for "parameters"?

**Comment by roycaihw** [comment]
@scottilee You can find examples in https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json. Look for delete operations defined under paths like:
```
/api/v1/pods
/api/v1/namespaces/{namespace}/pods
/api/v1/nodes
/apis/apps/v1/deployments
/apis/apps/v1/namespaces/{namespace}/deployments
```
