### ISSUE TITLE
Does gen support C/C++ ?

### ISSUE THREAD

**Issue by ityuhui** [kubernetes-client/gen#132]
Hi, all
I have not found any generator for C/C++.  Does gen support these two programming lauguages ?
Thanks.

**Comment by ityuhui** [comment]
I made below steps and generated C code.

1.  
```bash
cp openapi/go.sh openapi/c.sh
cp openapi/go.xml openapi/c.xml 
```

2. Update the 2 files by changing the text "go" to "c"

3.  Follow the readme to generate

Can I make a PR to this repo ?

**Comment by yue9944882** [comment]
iiuc, creating new language support in this org needs at least two maintainer's sponsorship..

@brendandburns

**Comment by tomplus** [comment]
It pops up sometimes... https://groups.google.com/forum/#!topic/kubernetes-dev/IUo8rdUQ2o8 It's not difficult to generate the library but more important is to have community which uses it and gives feedback.

**Comment by brendandburns** [comment]
@ityuhui I'm supportive of such a PR, I'd be happy to co-own a C/C++ client library.

Please send the PR, and I'll work to get the repo created.

**Comment by ityuhui** [comment]
Hi @brendandburns 
I'm pleased to send this PR to support C. But after I got the C client code generated by gen. It cannot be compiled successully. Lots of build errors need to be handled by manul.  
e.g.  
1. object.h is lost
2. some filed name is C language keywork, e.g.  enum, continue 
3. some filed name including "-" are not accpeted by C compiler.   e.g.  int x-b-c 
...
I think this is the defect of the C generator of https://github.com/OpenAPITools/openapi-generator.  So do you still want to accept this PR to support C now ? After all, the generated C client code cannot be used now.

**Comment by brendandburns** [comment]
No, we should make sure it's working code... Have you tried the C++ generator?

**Comment by ityuhui** [comment]
@brendandburns 

No.  I have not.  I need a pure C client library now because my program is written by pure C.
But I can try C++ ( cpprestsdk ) generator some time later and append the results here.

**Comment by brendandburns** [comment]
It's up to you, you can also work with the openapi folks to make the generator more useful. I've found they're very responsive to pull requests...

**Comment by ityuhui** [comment]
I'm working with OpenAPI-generator team now and will provide a C-libcurl client for kubernetes some times later.

**Comment by brendandburns** [comment]
Cool, looking forward to it!

**Comment by ityuhui** [comment]
Hi @brendandburns 

I have created the c language generator (c.sh, c.xml).  The c client library for kubernetes can be generated successfully.

And I have fixed all blocking issues in OpenAPI-Generator and now the c client can work well. ( e.g.  created a pod in kubernetes cluster )

May I create a PR to sumbit c.sh and c.xml ?

**Comment by ityuhui** [comment]
Hi @brendandburns

May I create a PR to submit c.sh and c.xml or do I need do something else first ?


> Hi @brendandburns
> 
> I have created the c language generator (c.sh, c.xml). The c client library for kubernetes can be generated successfully.
> 
> And I have fixed all blocking issues in OpenAPI-Generator and now the c client can work well. ( e.g. created a pod in kubernetes cluster )
> 
> May I create a PR to submit c.sh and c.xml ?

**Comment by brendandburns** [comment]
Yep, that's all you need to do. Please send a PR.

Apologies for the delay in responding!

**Comment by ityuhui** [comment]
Thank you @brendandburns !

I have sent the PR #148

**Comment by ityuhui** [comment]
Hello @yue9944882 @tomplus 

For creating a new repo "kubernetes-client/c" (https://github.com/kubernetes/org/issues/1700),  I'm required to apply for the org membership to @kubernetes-client. 

Could you please sponsor/approve me when I create a request? Thank you!

**Comment by brendandburns** [comment]
@ityuhui I will sponsor you for org membership.

**Comment by ityuhui** [comment]
Thank you @brendandburns !

**Comment by palnabarun** [comment]
This is very interesting.

Thank you @ityuhui for adding in the generator.

Let me know if you would need any help navigating the client ecosystem.

PS: I am helping in the maintenance of the Python client.

**Comment by ityuhui** [comment]
Thank you @palnabarun ！
It's very kind of you that give me the help.  
According to [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements), I need 2 sponsors to join the  @kubernetes-client. Could you please sponsor me in addition to @brendandburns ?

**Comment by palnabarun** [comment]
@ityuhui Sorry I saw this message late. Unfortunately, since I am not an approver/reviewer I couldn't have sponsored your membership.

However, I see that you have joined the organization already. Welcome! :fireworks:

**Comment by ityuhui** [comment]
Thank you @palnabarun. I believe I will certainly ask your help in the client library ecosystem in future.

**Comment by ityuhui** [comment]
Hi all

Thank you for your great help ( especially @brendandburns  ).  Now kubernetes-client/gen has a c generator and the c client https://github.com/kubernetes-client/c is working in progress now. 

I think I can close this issue now.

RP/issue/code review/help to the c client is greatly appreciated. Thank you in advance.
