### ISSUE TITLE
Update openapi-generator for typescript to v4.1.3

### ISSUE THREAD

**Issue by b1zzu** [kubernetes-client/gen#135]
With the 4.1.3 version of oepnapi-generator they have fixed a major issue https://github.com/OpenAPITools/openapi-generator/issues/3872 that was a main painful point in debugging errors. I would like to see this fix integrated into the `@kubernetes/client-node` library, but I saw that we first need to update the openapi-generator version in this project.
https://github.com/kubernetes-client/gen/blob/795993978f8563a9c09089993be4d2b97d492eec/openapi/typescript.sh#L49

**Comment by b1zzu** [comment]
I saw that the kuebernetes-client/javascript repo is overwriting this variable so probably there is no need to update it also here

**Comment by brendandburns** [comment]
ok, I'm going to close this here then.

Thanks!
