### ISSUE TITLE
preprocesing swagger.json makes operationId duplicated

### ISSUE THREAD

**Issue by tomplus** [kubernetes-client/gen#145]
The script `preprocess_spec.py` removes "tags" from `operationId` downloaded from K8s spec:

https://github.com/kubernetes-client/gen/blob/09f7470cab46c32e2e3458e6c98161829db88c44/openapi/preprocess_spec.py#L102

and it makes that some operationId's become duplicated but they should be unique.

The latest version of openapi-generator (>4.x) has additional validations which complains about that:

```
-attribute paths.'/apis/node.k8s.io/v1beta1/runtimeclasses/{name}'(delete).operationId is repeated
-attribute paths.'/apis/rbac.authorization.k8s.io/'(get).operationId is repeated
-attribute paths.'/apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}'(put).operationId is repeated
[~300 similar errors]
```

We can disable this validation or fix our script by removing this replacing step - is this replacement necessary?

**Comment by tomplus** [comment]
It looks like this behavior is crucial. OperationId is used to build method name and we have the same name in different API versions (beta, alfa etc).

**Comment by roycaihw** [comment]
Have you tried removing the replacing step? 

> It looks like this behavior is crucial. OperationId is used to build method name and we have the same name in different API versions (beta, alpha etc).

Yes, that's what I though it does. Without the replacing step we would have the API versions in the method names, which would be a breaking change and a more verbose UX.

Having the same method name in different API versions worked for us. Is there any reason that openapi-generator enforces unique operationID across all modules?

**Comment by tomplus** [comment]
It's required by the OpenAPI spec: https://swagger.io/specification/#operationObject

**Comment by roycaihw** [comment]
> It's required by the OpenAPI spec: https://swagger.io/specification/#operationObject

Fair enough. I think keeping the old method names is a better UX and is also backwards compatible. In the meantime, I'm not sure what signals does the openapi-generator spec validation give us. If it adds value on top of the other testing we have (e.g. client e2e tests), we may consider doing things like

1. dry-run the validation before preprocessing, and then disable validation for the processed spec
2. remove the replacing step in preprocessing, and add a replacing step in a "postprocessing"
