### ISSUE TITLE
Missing IoK8sApimachineryPkgApisMetaV1ObjectMeta in generated classes

### ISSUE THREAD

**Issue by franck102** [kubernetes-client/gen#159]
After following the instructions in generate-model-from-third-party-resources.md the classes generated have references to a `io.kubernetes.client.models.IoK8sApimachineryPkgApisMetaV1ObjectMeta`
which I cannot find anywhere?

The cluster version is 1.15 (minikube) and it contains a number of CRDs from the prometheus-operator (https://github.com/coreos/prometheus-operator).

Here is a typical snippet from the generated code:

```
ComCoreosMonitoringV1PodMonitor.java:
    public static final String SERIALIZED_NAME_METADATA = "metadata";
    @SerializedName(SERIALIZED_NAME_METADATA)
    private IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata = null;
```
The commands I used:
```
    kc get --raw="/openapi/v2" > openapi.json
    docker run -i --rm yue9944882/java-model-gen < openapi.json | tar -xzf - -C ./tmp
```

**Comment by franck102** [comment]
The correct class is
`io.kubernetes.client.openapi.models.V1ObjectMeta`

and everything works fine after manually updating the generated code.

**Comment by yue9944882** [comment]
this is fixed in `yue9944882/java-model-gen:v0.0.3` plz retry w/ that image

**Comment by brendandburns** [comment]
I think this can be closed?

**Comment by yue9944882** [comment]
/close

as this is addressed
