### ISSUE TITLE
Support client generation for custom resources

### ISSUE THREAD

**Issue by LittleBaiBai** [kubernetes-client/gen#175]
Currently the `java_crd_cmd.sh` script only generates models for CRD but not the API clients. It would be great to also generate API clients for custom resources so we don't need to use `GenericKubernetesApi` or `CustomObjectsApi` in our controller code. 

The generator knows how to generate API client for native kubernetes resources, so we can update `preprocess_spec.py` to keep the API endpoints for custom resources in CRD_MODE.

**Comment by brendandburns** [comment]
Closing this issue since #176 merged.
