### ISSUE TITLE
[Java] generics not being set

### ISSUE THREAD

**Issue by abelsromero** [kubernetes-client/gen#179]
Seems that last commit https://github.com/kubernetes-client/gen/commit/7ba97cc4c7bdac64ace24f85461776877e9b728e has made that List properties do not include the generic type.
See for instance how an unchanged property is now generated:
![image](https://user-images.githubusercontent.com/5781153/104030462-bada1f00-51cb-11eb-8b7d-4a7a356a4cea.png)

Running with the previous https://github.com/kubernetes-client/gen/commit/f04504fc2e4ae73e7335a7337bfa552b32eb2031 does not have the issue.

**Comment by brendandburns** [comment]
Is this a problem? Type inference in Java should do the right thing here.

**Comment by abelsromero** [comment]
> Is this a problem?

Not really, just wondering if this was on purpose since it got me by surprise when checking generated code changes.

**Comment by brendandburns** [comment]
Thanks, closing.
