### ISSUE TITLE
preprocess_spec.py generates invalid Swagger json

### ISSUE THREAD

**Issue by ceridwen** [kubernetes-client/gen#19]
When I tried to use https://github.com/Trax-air/swagger-parser on the json generated by calling `preprocess_spec.py release-1.6 kubernetes.json`, it complained that the json was invalid:

```
ValueError: swagger_kubernetes.json is not a valid swagger2.0 file: {'schema': {'type': 'object'}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['post']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/apis/{group}/{version}/{plural}']['post']['responses']['201']:
    {'schema': {'type': 'object'}}
```

I double-checked this with https://hub.docker.com/r/swaggerapi/swagger-validator/, which suggests that it is invalid.  swagger-codegen still accepts it so apparently swagger-codegen's validation isn't as strict, but this still makes it hard to use other tools on it.

**Comment by ceridwen** [comment]
Further investigation shows that the problem comes from adding the custom objects, because with that removed, the modified spec validates.

**Comment by ceridwen** [comment]
Running `swagger-codegen validate` gives a more informative error:

```
Validating spec file (swagger_kubernetes.json)
attribute paths.'/apis/{group}/{version}/{plural}'(post).201.description is missing
attribute paths.'/apis/{group}/{version}/namespaces/{namespace}/{plural}'(post).201.description is missing
Exception in thread "main" io.swagger.codegen.cmd.ValidateException
	at io.swagger.codegen.cmd.Validate.run(Validate.java:34)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

I tried adding the description fields with placeholders and that seemed to work.

**Comment by mbohlool** [comment]
Thanks for reporting. Can you add a relevant description and send a PR for it? Otherwise let me know and I will do it.

**Comment by ceridwen** [comment]
I'm not sure what role these two paths play in the Python client, otherwise I would.  If you can tell me what they do, I can try to write descriptions for them.
