### ISSUE TITLE
Resources starting with "io.k8s" being considered builtin prevents Volume Snapshot models generation

### ISSUE THREAD

**Issue by gregth** [kubernetes-client/gen#212]
I tried to generate models for Volume Snapshots, as follows:
```console
$ bash ./python-crd-cmd.sh -n io.k8s.storage.snapshot < swagger.json
```
This produced no models. 

I inspected the code and it turns out that resources starting with "io.k8s" are considered built:

https://github.com/kubernetes-client/gen/blob/291f9a6ca5004cc91cfc4a744abf129c639d5682/openapi/preprocess_spec.py#L307-L316

This does not hold for (at least) Volume Snapshot resources which are well-known CRDs. 

I tweaked a few lines of the script and here is a list of the Resources that were initially ignored, in my case:

```
io.k8s.storage.snapshot.v1alpha1.VolumeSnapshot
io.k8s.storage.snapshot.v1alpha1.VolumeSnapshotClass
io.k8s.storage.snapshot.v1alpha1.VolumeSnapshotClassList
io.k8s.storage.snapshot.v1alpha1.VolumeSnapshotContent
io.k8s.storage.snapshot.v1alpha1.VolumeSnapshotContentList
io.k8s.storage.snapshot.v1alpha1.VolumeSnapshotList
```

**Comment by gregth** [comment]
Let's discuss if anyone else has bumped onto this before, possible solutions, and I proceed with a PR to fix this, if you'd like to.

**Comment by brendandburns** [comment]
I don't think anyone else has hit this. Feel free to add a flag to optionally disable that check

**Comment by gregth** [comment]
Instead of adding an extra argument, we can fix this by modifying this if-else statement:
https://github.com/kubernetes-client/gen/blob/34ea9c4d4e0c6aeb1c41858b2b230adac3bacfe3/openapi/preprocess_spec.py#L311-L320

so that it does not ignore `io.k8s` if the user has explicitly specified a `KUBERNETES_CRD_GROUP_PREFIX` that contains `k8s.io`:

```python
def filter_api_group(spec):
    models = {}
    for k, v in spec['definitions'].items():
        if k.startswith(os.environ.get('KUBERNETES_CRD_GROUP_PREFIX')):
            models[k] = v
        elif k.startswith("io.k8s"):
            print("Removing builtin Kubernetes Resource %s" %k)
        else:
            print("Ignoring Custom Resource %s" %k)
    spec['definitions'] = models

```

@brendandburns what do you think? If we agree I can PR this and close this issue.

**Comment by gregth** [comment]
This issue was resolved by PR https://github.com/kubernetes-client/gen/pull/223.
