### ISSUE TITLE
IntOrString type is not defined in typescript-fetch generated code

### ISSUE THREAD

**Issue by adamkovalsky** [kubernetes-client/gen#217]
It looks like `typescript-fetch.xml` maps the `IntToString` type to be imported from `../../types`, I'm not sure what this refers to, but the resulting code has unresolved imports (and the import mapping seems to be ignored as far as I can tell).

**Comment by brendandburns** [comment]
fwiw, typescript-fetch is not widely used.

You need a custom definition for the IntToString class, you could use the one here:

https://github.com/kubernetes-client/javascript/blob/d44fa64da440559b55f0b70f30271b9d3097f3d2/src/types.ts#L16

**Comment by adamkovalsky** [comment]
@brendandburns I've tried this, but even if I put this definition in a `types.ts` file in (what I assume is) the right path, I couldn't get the generator to pick it up and use it correctly. Any idea what I could be missing?
