### ISSUE TITLE
Delete `client-gen-with-openapi-generator` container after it has run.

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [kubernetes-client/gen#226]
Running `ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.6 /generate.sh` to create model classes from CRD yaml utilises this project. Of the several shell scripts that gets triggered, one of them is `openapi/openapi-generator/client-generator.sh`. This shell script builds and runs a container from `openapi/openapi-generator/Dockerfile` during runtime of the script. The problem is after the created container has been run, it doesn't clean up after itself and keeps the created container. Thus a new container is built and left after running each time the CRD build script is triggered. This quickly creates lots of stopped containers.

The proposal is to add an `--rm` argument during the execution of the built container so that it gets removed after it is stopped.

I don't think that the container needs to be kept after it is stopped.

This will require a very small PR which I am more than happy to provide.

**Comment by SayakMukhopadhyay** [comment]
Apologies for the ping @brendandburns but I believed that this issue might have been missed.

**Comment by brendandburns** [comment]
Thanks for reporting this, a PR would be welcome to clean up these images.
