### ISSUE TITLE
Dubious Ownership error for /source/openapi-generator

### ISSUE THREAD

**Issue by maly7** [kubernetes-client/gen#236]
When running the generator inside the container, the following error is reported, and generation fails.

```
/source/openapi-generator /
fatal: detected dubious ownership in repository at '/source/openapi-generator'
To add an exception for this directory, call:

	git config --global --add safe.directory /source/openapi-generator
```

If it helps, I'm running the generator using `java-crd-cmd.sh`:

```bash
java-crd-cmd.sh -n com.vmware.tanzu.apps.config -p com.vmware.tanzu.acs -l 2 -h true -o /tmp/gen-output -g true
```

For now, I've worked around the issue by adding `RUN git config --system --add safe.directory '/source/openapi-generator'` in my [fork](https://github.com/maly7/gen/blob/maly7/fix-dubious-ownership-error/openapi/openapi-generator/Dockerfile#L31). I'm happy to contribute the change, but I wasn't sure if this would be the best fix.

**Comment by ityuhui** [comment]
I agree with @maly7's fix

And I made a PR for maintainers to review this solution.
