### ISSUE TITLE
Generated Ruby client has a few issues

### ISSUE THREAD

**Issue by slithernix** [kubernetes-client/gen#240]
First off, I have to enable skipValidation to not validate the spec or I get a whole bunch of errors:

```
[WARNING] /output_dir/swagger.json [0:0]: unexpected error in Open-API generation
org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 90, Warning count: 1
```

I am not going to paste all the errors, but most of them are like this snippet:

```
	-attribute paths.'/apis/events.k8s.io/v1/'(get).operationId is repeated
	-attribute paths.'/apis/internal.apiserver.k8s.io/'(get).operationId is repeated
	-attribute paths.'/apis/events.k8s.io/v1/namespaces/{namespace}/events'(post).operationId is repeated
	-attribute paths.'/apis/rbac.authorization.k8s.io/'(get).operationId is repeated
	-attribute paths.'/apis/certificates.k8s.io/v1alpha1/'(get).operationId is repeated
	-attribute paths.'/apis/coordination.k8s.io/'(get).operationId is repeated
``` 

Next up, this is small, but when you run a "gem build," on the resultant generated code, the gemspec issues a warning due to the license type:

```
WARNING:  license value 'Apache V2' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean 'Apache-1.0', 'Apache-1.1', 'Apache-2.0'?
```

Now, the more severe issue i've run into so far, there appears to be a bug in URL construction in the base_url() or server_url() method in lib/kubernetes/configuration.rb. If I set up a connection and try to execute an API, I get:

```
[7] pry(main)> client.list_pod_for_all_namespaces()
Kubernetes::ApiError: URL using bad/illegal format or missing URL
HTTP status code: 0
from /var/lib/gems/3.0.0/gems/kubernetes-1.23.17/lib/kubernetes/api_client.rb:62:in `call_api'
```

So, I went into lib/kubernetes/configuration.rb, and I edited line 193 in the base_url method to be:

```
return "#{scheme}://#{[host, base_path].join('/').gsub(/\/+/, '/')}".sub(/\/+\z/, '') if index == nil or index == 0
```

instead of:

```
return "#{scheme}://#{[host, base_path].join('/').gsub(/\/+/, '/')}".sub(/\/+\z/, '') if index == nil
```

I'm not sure that's a proper fix, but after doing this I can execute APIs.

LMK if you need more info.

**Comment by brendandburns** [comment]
Thanks for the report!

I don't think the Ruby library is maintained by anyone currently. (we should perhaps delete it, or get an active maintainer)

You may be better off with one of the community maintained clients:
https://kubernetes.io/docs/reference/using-api/client-libraries/#community-maintained-client-libraries

I'll leave this open as a reminder that we should figure out what we're doing here, but I don't think there will be rapid progress in the near term.

**Comment by slithernix** [comment]
would be a shame to delete it, ruby is a great language for ops scripting. the API seems to work fine so far in my usage. unfortunately i don't have the chops or the time to fix the generator.

**Comment by 2rs2ts** [comment]
> Now, the more severe issue i've run into so far, there appears to be a bug in URL construction in the base_url() or server_url() method in lib/kubernetes/configuration.rb. If I set up a connection and try to execute an API, I get:

Possibly related? https://github.com/kubernetes-client/ruby/pull/64

Of course, it won't do much good to know whether that's related if there's no one to merge that PR and maintain the official client anyway.

**Comment by slithernix** [comment]
surely there is a competent ruby dev out there who wants to help the k8s project... i am just an absolute git-r-done hack with barely any temporal resources anyways...
