### ISSUE TITLE
Need updates java open-api-tool build version to v6.6.0

### ISSUE THREAD

**Issue by dasarathirout** [kubernetes-client/gen#246]
Current java client generation script [kubernetes-client/gen/openapi/java.sh](https://github.com/kubernetes-client/gen/blob/master/openapi/java.sh#L52)  uses [OpenAPITools v4.3.1 ](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.3.1) which unable to build with configOptions `<useJakartaEe>true</useJakartaEe>` and  generate code with  `javax.annotation.*` instead of useing `jakarta.annotation.*`. 

Build script need update of [OpenAPITools-v6.6.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.6.0 )  recent stable version. 

Dependent issue javax to jakarta package namespaces : [kubernetes-client/-java-issues/2606 ](https://github.com/kubernetes-client/java/issues/2606)

**Comment by dasarathirout** [comment]
Open API Tool version updated, [PR-247](https://github.com/kubernetes-client/gen/pull/247)

**Comment by brendandburns** [comment]
Closing this issue because #247 has merged.
