### ISSUE TITLE
custom_objects_api should have a method `list_custom_object_for_all_namespaces`

### ISSUE THREAD

**Issue by davidxia** [kubernetes-client/gen#268]
### What is the feature and why do you need it:

Similar to the core_v1_api like [list_pod_for_all_namespaces](https://github.com/kubernetes-client/python/blob/041103952a93d1fa7a4478f972b581374f953ae6/kubernetes/docs/CoreV1Api.md#list_pod_for_all_namespaces), the [custom_objects_api](https://github.com/kubernetes-client/python/blob/041103952a93d1fa7a4478f972b581374f953ae6/kubernetes/docs/CustomObjectsApi.md) should have a method `list_custom_object_for_all_namespaces`.

### Describe the solution you'd like to see:

`list_custom_object_for_all_namespaces` calls endpoint `/apis/{group}/{version}/{plural}` to get custom objects in all namespaces.

> Although `list_custom_object_for_all_namespaces` and `list_cluster_custom_object` happens to talk to the same API endpoint, it may be better to have a `list_custom_object_for_all_namespaces` method for documentation purpose. https://github.com/kubernetes-client/java/issues/941#issuecomment-623052547 is the right way to fix this issue. Since this issue affects multiple clients, would you mind filing an issue in https://github.com/kubernetes-client/gen about fixing the openapi spec?

— https://github.com/kubernetes-client/python/issues/1377#issuecomment-827095911

**Comment by davidxia** [comment]
Is this possible?

> OpenAPI defines a unique operation as a combination of a path and an HTTP method. This means that two GET or two POST methods for the same path are not allowed

— https://swagger.io/docs/specification/paths-and-operations/

**Comment by brendandburns** [comment]
We could consider using the hashtag approach as described here:

https://github.com/OAI/OpenAPI-Specification/issues/182#issuecomment-771566673

That may work. In general that discussion has numerous people trying to solve similar issues.

**Comment by davidxia** [comment]
@brendandburns thanks! I made a PR #269

**Comment by brendandburns** [comment]
Closed via #269
