### ISSUE TITLE
Add annotationLibrary to java configuration

### ISSUE THREAD

**Issue by cache-sk** [kubernetes-client/gen#270]
There are two issues in java client since version 20.0.0 about problems with native build due not registering model during processAot task:
- https://github.com/kubernetes-client/java/issues/3134 
- https://github.com/kubernetes-client/java/issues/3271 

Main problem is missing swagger annotation ApiModel, which is used to identify model classes in AOT Processor.

I have recently discovered in [openapi generator docs](https://openapi-generator.tech/docs/generators/java/), that `annotationLibrary` property now defaults to `none`.

So, solution for that issues should be adding line:

`<annotationLibrary>swagger1</annotationLibrary>`

to [java.xml](https://github.com/kubernetes-client/gen/blob/6b9189ae4e18cd39e429fdf31fa46127a4b7939d/openapi/java.xml#L106) near line where is `useJakartaEe` set to `true`.

I tried it and it did indeed generate swagger ApiModel annotations. 

I assume that it will also solve the mentioned issues in the java client after regenerating models.

**Comment by brendandburns** [comment]
Happy to take a PR for this.

Thanks!

**Comment by cache-sk** [comment]
@brendandburns Created PR #271 as requested..
