### ISSUE TITLE
missing support for custom object status/scale api

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes-client/gen#71]
since kubernetes 1.11 the custom object status/scale api is in beta:
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource

But the generator does not support it as it is missing in `openapi/custom_objects_spec.json`
If this is not intentional due to the beta status of the api it would be very helpful to have this added so clients can generate code for it.

**Comment by brendandburns** [comment]
This isnt intentional. We should fix, would love a pr...

**Comment by juliantaylor** [comment]
I'd love to but I can't find any documentation how this file is generated.

**Comment by brendandburns** [comment]
You just need to edit that JSON Swagger file to have the new object, then everything "just works" when you regenerate...

See the code here:
https://github.com/kubernetes-client/gen/blob/7d7ec1cfee81d05bd3d23715eb36d831a5eee4fe/openapi/preprocess_spec.py#L33

https://github.com/kubernetes-client/gen/blob/7d7ec1cfee81d05bd3d23715eb36d831a5eee4fe/openapi/preprocess_spec.py#L105

**Comment by juliantaylor** [comment]
yeah sure, but do you manually write that swagger file? It looks generated.

**Comment by mbohlool** [comment]
This is the file: https://github.com/kubernetes-client/gen/blob/master/openapi/custom_objects_spec.json

It is not auto-generated. The code Brendan referenced is where this spec get merged with the main spec (that one is generated). You can edit that file and add /scale and /status endpoints.

**Comment by juliantaylor** [comment]
yes thanks, I have already created a PR with the additions
