### ISSUE TITLE
migrate from swagger-codegen to openapi-generator

### ISSUE THREAD

**Issue by tomplus** [kubernetes-client/gen#93]
This repo uses the swagger-codegen, which is not actively maintained, at least from a my point of view. It makes lots of hacks like post-generation patching and it’s very hard to maintain these scripts. 

For instance - here is a list of PRs which are ready to merge but are not merged yet and had to be applied as patches in Python generator:

- https://github.com/swagger-api/swagger-codegen/pull/7905 (Mar 25, waiting)
- https://github.com/swagger-api/swagger-codegen/pull/8061 (Apr 24, waiting)
- https://github.com/swagger-api/swagger-codegen/pull/8204 (May 17, waiting)
- https://github.com/swagger-api/swagger-codegen/pull/8401 (Jul 8, finally merged)
- https://github.com/swagger-api/swagger-codegen/pull/8797 (Oct 9, waiting)

A lot of contributors moved from the swagger-codegen to the new project - [openapi-generator](http://github.com/openapitools/openapi-generator). Basically it’s a fork of swagger-codegen but it’s actively developed and it gains popularity very fast.

All above PRs are already ported and merged to the openapi-generator:

- https://github.com/OpenAPITools/openapi-generator/pull/1387 (merged)
- https://github.com/OpenAPITools/openapi-generator/pull/107 (merged)
- https://github.com/OpenAPITools/openapi-generator/pull/519 (merged)
- https://github.com/OpenAPITools/openapi-generator/pull/1211 (merged)

What do you think about changing generator? Is it possible? I’ll be happy to work on it...

**Comment by brendandburns** [comment]
Yes we should do this. If you have cycles for the PR that's awesome. Otherwise I'll try to get to it.

**Comment by mbohlool** [comment]
There is a document for the migration: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/migration-from-swagger-codegen.md

**Comment by mbohlool** [comment]
@tomplus Thanks for doing this. Please make sure at least supported client such as [python](https://github.com/kubernetes-client/python) or [java](https://github.com/kubernetes-client/java) would create identical client before switching to openapi-gen. There are documents (e.g. [this](https://github.com/kubernetes-client/python/blob/master/devel/release.md)) that may need to be updated to access the right generator.

**Comment by tomplus** [comment]
@mbohlool Thanks for your advice. I'll check these clients and update docs too.

Some changes in generated code will appear because clients are based on very old version of generator - java client: https://github.com/kubernetes-client/gen/blob/d0821e65aa3474ce69b6bd64219d9c2082c391b7/openapi/java.sh#L52 committed on Aug 9, 2017

python: https://github.com/kubernetes-client/gen/blob/d0821e65aa3474ce69b6bd64219d9c2082c391b7/openapi/python.sh#L49 committed on Sep 26, 2017

I hope we'll get working clients with a small set of non-breaking changes.

**Comment by brendandburns** [comment]
I tried the Java generator. It seems to fail on the `type-mappings` directive. I'm working with the maintainers of `openapi-generator` to see if there's a fix.

@tomplus, I will own this for Java and Typescript.

Thanks!

**Comment by tomplus** [comment]
@brendandburns Thanks :+1: I'm working on the Python client.

**Comment by ackintosh** [comment]
I started working on [the Ruby client](https://github.com/kubernetes-client/ruby). 💨

**Comment by ackintosh** [comment]
memo: the haskell client has been switched. https://github.com/kubernetes-client/gen/pull/108

**Comment by ackintosh** [comment]
UPDATE: the Ruby client generator has been switched to openapi-generator.  https://github.com/kubernetes-client/gen/pull/103

**Comment by 007** [comment]
@tomplus any update on the Python client?

I'm waiting on https://github.com/swagger-api/swagger-codegen/pull/8061 to get https://github.com/kubernetes-client/python/issues/411 resolved. It seems you made some progress on that, I haven't had a chance to update and test my broken code to see if the workaround fixes the hang.

**Comment by tomplus** [comment]
@007 The PR (#97) is ready to review, I hope it will be merged soon.

**Comment by brendandburns** [comment]
@tomplus we just switched the Java generator. At this point I think everyone is on openapi?

Can we close this issue?

**Comment by tomplus** [comment]
@brendandburns  Wow! Great news. I did some checks and it looks like csharp client still uses the old generator. Javascript client also but it likely doesn't use this repo to generate (I suggest to remove its script to avoid confusion). Python-asyncio needs some cleanups, one unused variant uses swagger - I'll remove it.

Should we remove swagger-codegen directories and files when all generators has been switched or maybe you want to leave it for a while?

**Comment by brendandburns** [comment]
csharp uses autorest, which is a totally different generator.

Javascript can be removed as we're using typescript.

I'll send PRs to do the cleanup.
